### ISSUE TITLE
Cannot add the extension...

### ISSUE THREAD

**Issue by aditya324jhj** [moeinfatehi/Admin-Panel_Finder#3]
I cannot add the extension in burpsuite. This is the error code -->
java.lang.Exception: Extension class is not a recognized type
	at burp.ffq.W(Unknown Source)
	at burp.ffq.P(Unknown Source)
	at burp.yfb.Q(Unknown Source)
	at burp.yyz.o(Unknown Source)
	at burp.doo.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by moeinfatehi** [comment]
have you tried the jar file behind the releases part or compiled it yourself?

**Comment by moeinfatehi** [comment]
I've tested with JDK 8,13,21
all versions work
